// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvryaynijbfizvsghwko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2cnlheW5pamJmaXp2c2dod2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NjEwMzIsImV4cCI6MjA3MjQzNzAzMn0.lzcIVxRzJ2MFEXSjmQ7HI6k3IUhTBE5HNWxBkbNRXKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});